<a href="https://colab.research.google.com/github/NimishSinghChouhan/Smart-Bridge-AI/blob/main/Smart_Bridge_AI_Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 4

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3]) 
arr

array([1, 2, 3])

In [ ]:
type(arr) # nd means n dimensions array

numpy.ndarray

In [ ]:
# Finding dimensions
arr.ndim

1

In [ ]:
#Arange - Printing a range of values
np.arange(13,19)


array([13, 14, 15, 16, 17, 18])

In [ ]:
range(13,19)

range(13, 19)

In [ ]:
for i in range(13,19):
  print(i)

13
14
15
16
17
18


In [ ]:
np.arange(13,40,4) # (starting ending,skipped value)

array([13, 17, 21, 25, 29, 33, 37])

In [ ]:
np.arange(13,40,4,dtype=float)

array([13., 17., 21., 25., 29., 33., 37.])

In [ ]:
#linespace 
np.linspace(0,10,3) # (starting,ending,how many divisions)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
range(13,19)

range(13, 19)

In [ ]:
np.arange(13,40,4),np.arange(13,40,4,dtype=float)

(array([13, 17, 21, 25, 29, 33, 37]),
 array([13., 17., 21., 25., 29., 33., 37.]))

In [ ]:
np.zeros(10), np.ones(10,dtype=int)
# default datatype for zeros and ones is float

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [ ]:
arr

array([1, 2, 3])

In [ ]:
#Argmax - Position of the max value (gives index of max value)
arr.argmax()

2

In [ ]:
arr2 = np.array([21,31,11,0,34,34])    

In [ ]:
arr2.argmax()

4

In [ ]:
max(arr2)

34

In [ ]:
arr

array([1, 2, 3])

In [ ]:
#Argmin - Position of the min value (gives index of min vale)
arr.argmin()

0

In [ ]:
arr2.argmin()

3

In [ ]:
arr2[2]=100

In [ ]:
arr2

array([ 21,  31, 100,   0,  34,  34])

In [ ]:
#Slicing & Indexing

In [ ]:
arr2[2:4]

array([100,   0])

In [ ]:
arr2[-4:]

array([100,   0,  34,  34])

In [ ]:
a=np.array([[1,3,2,4],[9,8,6,7]])
a

array([[1, 3, 2, 4],
       [9, 8, 6, 7]])

In [ ]:
a.ndim

2

In [ ]:
a[0]   # gives array at position 0

array([1, 3, 2, 4])

In [ ]:
a[0][2]  # gives elemnt at position 2 in 1st array

2

In [ ]:
_3d=np.array([[[1,3,2,4],[9,8,6,7],[23,43,52,6]]])   # everything here is on 0th index
_3d   #. number of brackets define dimensions

array([[[ 1,  3,  2,  4],
        [ 9,  8,  6,  7],
        [23, 43, 52,  6]]])

In [ ]:
_3d.ndim

3

In [ ]:
_3d[0]

array([[ 1,  3,  2,  4],
       [ 9,  8,  6,  7],
       [23, 43, 52,  6]])

In [ ]:
_3d[0][0]

array([1, 3, 2, 4])

In [ ]:
_3d[0][0][3]

4

In [ ]:
_3d[0][2][1:4]

array([43, 52,  6])

In [ ]:
_3da=np.array([[[1,3,2,4],[9,8,6,7]],[[2,4,5,6],[2,4,3,5]]])   
_3da

array([[[1, 3, 2, 4],
        [9, 8, 6, 7]],

       [[2, 4, 5, 6],
        [2, 4, 3, 5]]])

In [ ]:
_3da[1]

array([[2, 4, 5, 6],
       [2, 4, 3, 5]])

In [ ]:
_3da.ndim

3

In [ ]:
# Reshape
a=np.arange(12)  # Possib (6*2, 4*3)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(3,4) # (6,2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.random.rand(10)

array([0.47680163, 0.97594844, 0.0879675 , 0.97191108, 0.79793993,
       0.63493265, 0.75501304, 0.68109005, 0.01399199, 0.43494707])

In [ ]:
np.random.randint(2,100) #range

84

In [ ]:
a.sum()  # to find the sum of array

66

In [ ]:
# Sqrt & Log
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [ ]:
np.log(a)

<ipython-input-49-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [ ]:
np.log10(a)

<ipython-input-50-c769c8e1eb64>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269])

In [ ]:
# Absolute
b=-32
np.abs(b)

32

In [ ]:
# Pandas  - - Data Manupulation

# pandas----> 1) Series  & 2) Dataframe

import pandas as pd

In [ ]:
s = pd.Series(np.random.rand(6)) # if we just used np.random.rand we would get just values but here we are getting index also
s

0    0.481124
1    0.953468
2    0.183356
3    0.660450
4    0.999374
5    0.901354
dtype: float64

Indexing and Slicing possible in pd series

In [ ]:
s[4] # indexing

0.9993744061180961

In [ ]:
s[2:4] # slicing

2    0.183356
3    0.660450
dtype: float64

In [ ]:
s[0]=1234 # assigning also possible and is mutable
s

0    1234.000000
1       0.953468
2       0.183356
3       0.660450
4       0.999374
5       0.901354
dtype: float64

We can change the index in series, it is like serial number

In [ ]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
s.index = ['a','b','c','d','e',4]
s

a    1234.000000
b       0.953468
c       0.183356
d       0.660450
e       0.999374
4       0.901354
dtype: float64

In [ ]:
s[1] # here we are getting error bcz we have changed the index from 0123 to abcd

KeyError: ignored

In [ ]:
s['a']

1234.0

In [ ]:
s['b':'e']

b    0.953468
c    0.183356
d    0.660450
e    0.999374
dtype: float64

In [ ]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 4], dtype='object')

In [ ]:
s['b':]

b    0.953468
c    0.183356
d    0.660450
e    0.999374
4    0.901354
dtype: float64

In [ ]:
s[-2:-1]

e    0.999374
dtype: float64

In [ ]:
s[-4:-1]

c    0.183356
d    0.660450
e    0.999374
dtype: float64

In [ ]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 4], dtype='object')

In [ ]:
s[2:4]

c    0.183356
d    0.660450
dtype: float64

In [ ]:
s1=pd.Series(np.random.rand(12))
s1

0     0.982320
1     0.276768
2     0.612246
3     0.937778
4     0.404995
5     0.964806
6     0.671818
7     0.564406
8     0.148656
9     0.962933
10    0.206577
11    0.121724
dtype: float64

In [ ]:
s1[1:9:2]

1    0.276768
3    0.937778
5    0.964806
7    0.564406
dtype: float64