<a href="https://colab.research.google.com/github/NimishSinghChouhan/Smart-Bridge-AI/blob/main/Smart_Bridge_AI_Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 4

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
type(arr) # nd means n dimensions array

numpy.ndarray

In [5]:
# Finding dimensions
arr.ndim

1

In [6]:
#Arange - Printing a range of values
np.arange(13,19)


array([13, 14, 15, 16, 17, 18])

In [7]:
range(13,19)

range(13, 19)

In [8]:
for i in range(13,19):
  print(i)

13
14
15
16
17
18


In [9]:
np.arange(13,40,4) # (starting ending,skipped value)

array([13, 17, 21, 25, 29, 33, 37])

In [10]:
np.arange(13,40,4,dtype=float)

array([13., 17., 21., 25., 29., 33., 37.])

In [11]:
#linespace 
np.linspace(0,10,3) # (starting,ending,how many divisions)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
range(13,19)

range(13, 19)

In [14]:
np.arange(13,40,4),np.arange(13,40,4,dtype=float)

(array([13, 17, 21, 25, 29, 33, 37]),
 array([13., 17., 21., 25., 29., 33., 37.]))

In [15]:
np.zeros(10), np.ones(10,dtype=int)
# default datatype for zeros and ones is float

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [16]:
arr

array([1, 2, 3])

In [17]:
#Argmax - Position of the max value (gives index of max value)
arr.argmax()

2

In [18]:
arr2 = np.array([21,31,11,0,34,34])    

In [19]:
arr2.argmax()

4

In [20]:
max(arr2)

34

In [21]:
arr

array([1, 2, 3])

In [22]:
#Argmin - Position of the min value (gives index of min vale)
arr.argmin()

0

In [23]:
arr2.argmin()

3

In [24]:
arr2[2]=100

In [25]:
arr2

array([ 21,  31, 100,   0,  34,  34])

In [30]:
#Slicing & Indexing

In [29]:
arr2[2:4]

array([100,   0])

In [34]:
arr2[-4:]

array([100,   0,  34,  34])

In [37]:
a=np.array([[1,3,2,4],[9,8,6,7]])
a

array([[1, 3, 2, 4],
       [9, 8, 6, 7]])

In [38]:
a.ndim

2

In [41]:
a[0]   # gives array at position 0

array([1, 3, 2, 4])

In [42]:
a[0][2]  # gives elemnt at position 2 in 1st array

2

In [43]:
_3d=np.array([[[1,3,2,4],[9,8,6,7],[23,43,52,6]]])   # everything here is on 0th index
_3d   #. number of brackets define dimensions

array([[[ 1,  3,  2,  4],
        [ 9,  8,  6,  7],
        [23, 43, 52,  6]]])

In [44]:
_3d.ndim

3

In [49]:
_3d[0]

array([[ 1,  3,  2,  4],
       [ 9,  8,  6,  7],
       [23, 43, 52,  6]])

In [48]:
_3d[0][0]

array([1, 3, 2, 4])

In [46]:
_3d[0][0][3]

4

In [50]:
_3d[0][2][1:4]

array([43, 52,  6])

In [55]:
_3da=np.array([[[1,3,2,4],[9,8,6,7]],[[2,4,5,6],[2,4,3,5]]])   
_3da

array([[[1, 3, 2, 4],
        [9, 8, 6, 7]],

       [[2, 4, 5, 6],
        [2, 4, 3, 5]]])

In [56]:
_3da[1]

array([[2, 4, 5, 6],
       [2, 4, 3, 5]])

In [57]:
_3da.ndim

3